---
title: "My Storyboard at IAS - tabs"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard) # always
```

<!-- links -->
```{r}
map1link= "https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Tarea-Individual-2/raw/main/map1_buenas.rds"
viz1=url(map1link)

map2link= "https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Tarea-Individual-2/raw/main/map2_malas.rds"
viz2=url(map2link)

map3link= "https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Tarea-Individual-2/raw/main/map3_propuestas.rds"
viz3=url(map3link)

map4link= "https://github.com/CIENCIA-DE-DATOS-ESPACIALES-1IAS21-05A1/Tarea-Individual-2/raw/main/map4_completo.rds"
viz4=url(map4link)
```

## Sidebar {.sidebar}


## Column {.tabset .tabset-fade}


### Plan de Reubicación de Estaciones de Gasolina en Seattle

```{r}
readRDS(viz4)
```


### Estaciones de Gasolina con Ubicación Correcta

```{r}
readRDS(viz2)
```

### Estaciones de Gasolina en Conflicto

```{r}
readRDS(viz3)
```


### Nuevas Ubicaciones Propuestas

```{r}
readRDS(viz1)
```



